version: '3.7'

services:
  elasticsearch:
    image: docker.io/library/elasticsearch:7.6.0
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=311-cluster"
      - "node.name=only-node"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - de_network

      
  kibana:
    image: docker.io/library/kibana:7.6.0 
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - de_network

  nifi:
    image: docker.io/apache/nifi:latest
    ports:
      - "8443:8443"
    volumes:
      - ./nifi/data:/opt/nifi/nifi-current/data
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
